
import { Chapter, Media } from '@/types';

const MAX_RETRIES = 5;
const RETRY_DELAY = 1000;

export const fetchArticleContent = async (
  url: string, 
  retryCount = 0
): Promise<{ content: string; media: Media[] } | { error: string }> => {
  try {
    // In a real implementation, this would call a backend API to fetch and parse the article
    // For now, we'll simulate the process with a timeout
    
    // Simulate some failures to demonstrate retry logic
    if (Math.random() > 0.8 && retryCount < MAX_RETRIES - 1) {
      throw new Error('Simulated fetch failure');
    }
    
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // This is where we'd parse the article content and extract media
    // For now, return dummy content
    return {
      content: `<div class="article-content">
        <p>This is simulated content for the article at ${url}.</p>
        <p>In a real implementation, we would extract the actual content from the page using a backend service.</p>
        <p>The backend would use libraries like BeautifulSoup or Playwright to extract the clean content.</p>
      </div>`,
      media: [
        {
          type: 'image',
          url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1741&q=80',
          alt: 'Sample image from article'
        }
      ]
    };
    
  } catch (error) {
    // Implement retry logic
    if (retryCount < MAX_RETRIES) {
      console.log(`Retry ${retryCount + 1}/${MAX_RETRIES} for URL: ${url}`);
      await new Promise(resolve => setTimeout(resolve, RETRY_DELAY * (retryCount + 1)));
      return fetchArticleContent(url, retryCount + 1);
    }
    
    return {
      error: `Failed to fetch article after ${MAX_RETRIES} attempts: ${(error as Error).message}`
    };
  }
};

export const generateChapterSummary = async (title: string, content: string): Promise<string> => {
  try {
    // In a real implementation, this would call the Gemini API
    // For now, simulate with a timeout
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    return `This is a simulated 200-word summary of the chapter "${title}" that would normally be generated by the Gemini API. The summary would provide a concise overview of the article's main points and key takeaways, making it easy for readers to understand what the chapter contains before diving into the full content.`;
  } catch (error) {
    console.error('Error generating chapter summary:', error);
    return 'Failed to generate summary. You can edit this description manually.';
  }
};

export const extractTitleFromUrl = (url: string): string => {
  try {
    // Try to extract a readable title from the URL
    const urlObj = new URL(url);
    const pathSegments = urlObj.pathname.split('/').filter(Boolean);
    if (pathSegments.length > 0) {
      const lastSegment = pathSegments[pathSegments.length - 1];
      // Replace dashes, underscores with spaces and capitalize
      return lastSegment
        .replace(/[-_]/g, ' ')
        .replace(/\.\w+$/, '') // Remove file extensions
        .split(' ')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
    }
    
    // Fallback to domain name if path doesn't provide a good title
    return urlObj.hostname
      .replace(/^www\./, '')
      .split('.')
      .slice(0, -1)
      .join(' ')
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
      
  } catch (error) {
    return 'Untitled Article';
  }
};
