// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sltqciiudrqxivkuouwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdHFjaWl1ZHJxeGl2a3VvdXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTg1MjIsImV4cCI6MjA1NjczNDUyMn0.zE8JzdhAUBHTMIqboEuQ2Z74PA3hYZnQEHrtlr8kZrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);